change format to fstring literals
GrafeasGroup/tor_ocr pull request #13
Opened 2017-12-01 13:40 UTC by yukilikespie

2017-12-01 13:50 UTC, perryprog requested changes
See my review in the main tor repo. Again, I'm not sure if we're using single or double quotes, but we'll figure that out depending on what Ghost/Joker think

2017-12-01 13:50 UTC, perryprog commented on tor_ocr/errors.py
> +                f"Unrecognized error: Code {result['exit_code']}, {result['error_message']}: {result['error_details']}"
This line is too long

2017-12-01 13:50 UTC, perryprog commented on tor_ocr/main.py
> +            f'ERROR {result.status_code} with OCR:\n\nHEADERS:\n{repr(result.headers)}\n\nBODY:\n{repr(result.text)}'
This line is too long

2017-12-01 20:19 UTC, perryprog requested changes

2017-12-01 20:19 UTC, perryprog commented on tor_ocr/errors.py
> +                f"{result['error_message']}: {result['error_details']}"
Single quotes here and here

2017-12-01 20:21 UTC, perryprog approved these changes
I'm stupid nvm

2017-12-02 16:20 UTC, TheLonelyGhost approved these changes
Nothing blatantly wrong, though I'm unsure if following our pre-existing style in a part where we nest `result['error_message']` inside of an `f`-string would make it react differently if the `f`-string was with single- vs. double-quotes.

Not a big deal. It doesn't matter so much to me that I'd be willing to research it. 👍 Great work! Thanks!

2017-12-02 16:21 UTC, merged