Bugfix for issue #29 on tor repo
GrafeasGroup/tor_ocr pull request #37
Opened 2021-04-28 17:24 UTC by Pf441

The "Source" link of transcribot now redirects to this repo instead of the u/tor one.

Relevant issue: https://github.com/GrafeasGroup/tor/issues/210

## Description:

transcribot's "Source" link redirected to u/tor's repo instead of its one. This patch fixes the issue.

2021-04-28 19:02 UTC, TheLonelyGhost requested changes
Would you mind updating the changelog too? We generally put unreleased changes in a section at the top called `[UNRELEASED]`, but I see that will need to be recreated.

2021-04-30 16:05 UTC, Pf441 commented
Sure, can do! Is it on a file to edit?

2021-04-30 16:09 UTC, NGTmeaty commented
> Sure, can do! Is it on a file to edit?

https://github.com/GrafeasGroup/tor_ocr/blob/main/CHANGELOG.md

2021-05-01 08:04 UTC, Pf441 commented
Now it should be fine :)

2021-05-14 17:42 UTC, TheLonelyGhost approved these changes

2021-05-14 17:42 UTC, merged